# Generated by Django 4.1.1 on 2022-10-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='faculty_description',
            new_name='facility_description',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
