# Generated by Django 4.1.1 on 2022-10-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0002_rename_faculty_description_meeting_facility_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='units',
            field=models.CharField(max_length=20),
        ),
    ]
