# Generated by Django 4.1.1 on 2022-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0011_alter_profile_saved_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_sections',
            field=models.ManyToManyField(blank=True, to='louslist.section'),
        ),
    ]
