# Generated by Django 4.1.1 on 2022-11-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0012_alter_profile_saved_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('catalog_number', models.CharField(max_length=4)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='louslist.course'),
        ),
    ]
