# Generated by Django 4.1.1 on 2022-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0014_alter_course_catalog_number_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='louslist.profile'),
        ),
    ]
