# Generated by Django 4.1.1 on 2022-11-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0016_remove_profile_saved_courses_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_profile_set', to='louslist.profile'),
        ),
    ]
