# Generated by Django 4.1.1 on 2022-11-12 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0017_alter_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
