# Generated by Django 4.1.1 on 2022-11-12 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0019_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
